### ISSUE TITLE
Update the version on crates.io

### ISSUE THREAD

**Issue by morwoen** [xsleonard/rust-sdl2_image#41]
When I use

```toml
[dependencies]
sld2_image = "0.2.1"
```

The last version I saw on crates.io, downloads code from 2 months ago, which tries to  link to sld2-sys 0.2 while sdl2 is linking to 0.4. Hence I am getting this error:

```
native library `SDL2` is being linked to by more than one package, and can only be linked to by one package

  sdl2-sys v0.2.2
  sdl2-sys v0.4.0
```

The quick fix was to use the following config:

```toml
[dependencies.sld2_image]
git = "https://github.com/xsleonard/rust-sdl2_image.git"
```

I don't know how exactly you deploy new versions to crates.io. I assume bumping the version with 1 does it automatically? I can submit a pull request if somebody confirms that this would fix the issue?
